unless: << pipeline.parameters.api_triggered >>
jobs:
  - bump_version:
      context:
        - slack-app
        - deliverino
        - jira
      delivery: none

  - notify_android:
      context:
        - slack-app
        - deliverino
      production_delivery: false
      requires:
        - bump_version

  - notify_ios:
      context:
        - slack-app
        - deliverino
      production_delivery: false
      requires:
        - bump_version
