unless: << pipeline.parameters.api_triggered >>
jobs:
  - bump_version:
      context:
        - mattermost
        - deliverino
        - jira
      delivery: none
  - check_native:
      context:
        - mattermost

  - build_android:
      name: build_e2e_android
      build_config_name: integreat-e2e
      context:
        - mattermost
        - tuerantuer-google-play
        - tuerantuer-android
      requires:
        - bump_version
  - e2e_android:
      context:
        - mattermost
        - browserstack
      requires:
        - build_e2e_android

  - build_android:
      name: build_aschaffenburg_android
      build_config_name: aschaffenburg
      context:
        - mattermost
        - tuerantuer-google-play
        - tuerantuer-android
      requires:
        - bump_version
  - deliver_android:
      name: deliver_aschaffenburg_android
      build_config_name: aschaffenburg
      context:
        - mattermost
        - sentry
        - browserstack
        - tuerantuer-google-play
        - tuerantuer-android
      production_delivery: false
      requires:
        - check_native
        - e2e_android
        - build_aschaffenburg_android

  - notify_android:
      context:
        - mattermost
        - deliverino
      production_delivery: false
      requires:
        - deliver_aschaffenburg_android

  - build_ios:
      name: build_e2e_ios
      build_config_name: integreat-e2e
      context:
        - mattermost
        - tuerantuer-apple
        - tuerantuer-ios
      requires:
        - bump_version
  - e2e_ios:
      context:
        - mattermost
        - browserstack
      requires:
        - build_e2e_ios

  - build_ios:
      name: build_aschaffenburg_ios
      build_config_name: aschaffenburg
      context:
        - mattermost
        - tuerantuer-apple
        - tuerantuer-ios
      requires:
        - bump_version
  - deliver_ios:
      name: deliver_aschaffenburg_ios
      build_config_name: aschaffenburg
      context:
        - mattermost
        - sentry
        - browserstack
        - tuerantuer-apple
        - tuerantuer-ios
      production_delivery: false
      requires:
        - check_native
        - e2e_ios
        - build_aschaffenburg_ios

  - notify_ios:
      context:
        - mattermost
        - deliverino
      production_delivery: false
      requires:
        - deliver_aschaffenburg_ios
