unless: << pipeline.parameters.api_triggered >>
jobs:
  - build_ios:
      context:
        - slack-app
        - tuerantuer-apple
        - tuerantuer-ios
      build_for_delivery: true
  - e2e_ios:
      context:
        - slack-app
        - browserstack
      requires:
        - build_ios
